### ISSUE TITLE
potential issues on english mac os ?

### ISSUE THREAD

**Issue by anjungbae** [taggon/coffeefy#2]
first of all, i appreciate this convenient app.
however, i found it not working on my english mac os (or on macOS high sierra ver. 10.13.2 beta).

could anyone look into this potential issue?

thanks,

**Comment by taggon** [comment]
I don't think the language matters because I have been developing and using the app on my MBP with English macOS High Sierra v10.13.1. I suspect the beta version causes the problem. Can you try the app in a stable version? If the problem still exists, please give me details about "not working" status to let me take a look at it.

**Comment by anjungbae** [comment]
Dear Taegon Kim,

i tried uninstalling and installing the same current version (v.1.3.0)
again,
and it is working now!

however, i do not have what caused the previous malfunction unfortunately.
if i found same/similar problem, i will surely inform you further.

anyways, i really appreciate for your efforts developing this convenient
app.

thanks,
jungbae

**Comment by taggon** [comment]
Good to hear that your problem is solved. :)
